/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkspaceSettingsRouteImport } from './routes/workspace-settings'
import { Route as VisualizationDataRouteImport } from './routes/visualization-data'
import { Route as SourceDataRouteImport } from './routes/source-data'
import { Route as DecisionBriefsRouteImport } from './routes/decision-briefs'
import { Route as ChatRouteImport } from './routes/chat'
import { Route as IndexRouteImport } from './routes/index'

const WorkspaceSettingsRoute = WorkspaceSettingsRouteImport.update({
  id: '/workspace-settings',
  path: '/workspace-settings',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizationDataRoute = VisualizationDataRouteImport.update({
  id: '/visualization-data',
  path: '/visualization-data',
  getParentRoute: () => rootRouteImport,
} as any)
const SourceDataRoute = SourceDataRouteImport.update({
  id: '/source-data',
  path: '/source-data',
  getParentRoute: () => rootRouteImport,
} as any)
const DecisionBriefsRoute = DecisionBriefsRouteImport.update({
  id: '/decision-briefs',
  path: '/decision-briefs',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatRoute = ChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/decision-briefs': typeof DecisionBriefsRoute
  '/source-data': typeof SourceDataRoute
  '/visualization-data': typeof VisualizationDataRoute
  '/workspace-settings': typeof WorkspaceSettingsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/decision-briefs': typeof DecisionBriefsRoute
  '/source-data': typeof SourceDataRoute
  '/visualization-data': typeof VisualizationDataRoute
  '/workspace-settings': typeof WorkspaceSettingsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/chat': typeof ChatRoute
  '/decision-briefs': typeof DecisionBriefsRoute
  '/source-data': typeof SourceDataRoute
  '/visualization-data': typeof VisualizationDataRoute
  '/workspace-settings': typeof WorkspaceSettingsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/chat'
    | '/decision-briefs'
    | '/source-data'
    | '/visualization-data'
    | '/workspace-settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/chat'
    | '/decision-briefs'
    | '/source-data'
    | '/visualization-data'
    | '/workspace-settings'
  id:
    | '__root__'
    | '/'
    | '/chat'
    | '/decision-briefs'
    | '/source-data'
    | '/visualization-data'
    | '/workspace-settings'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ChatRoute: typeof ChatRoute
  DecisionBriefsRoute: typeof DecisionBriefsRoute
  SourceDataRoute: typeof SourceDataRoute
  VisualizationDataRoute: typeof VisualizationDataRoute
  WorkspaceSettingsRoute: typeof WorkspaceSettingsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/workspace-settings': {
      id: '/workspace-settings'
      path: '/workspace-settings'
      fullPath: '/workspace-settings'
      preLoaderRoute: typeof WorkspaceSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualization-data': {
      id: '/visualization-data'
      path: '/visualization-data'
      fullPath: '/visualization-data'
      preLoaderRoute: typeof VisualizationDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/source-data': {
      id: '/source-data'
      path: '/source-data'
      fullPath: '/source-data'
      preLoaderRoute: typeof SourceDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decision-briefs': {
      id: '/decision-briefs'
      path: '/decision-briefs'
      fullPath: '/decision-briefs'
      preLoaderRoute: typeof DecisionBriefsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat': {
      id: '/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof ChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ChatRoute: ChatRoute,
  DecisionBriefsRoute: DecisionBriefsRoute,
  SourceDataRoute: SourceDataRoute,
  VisualizationDataRoute: VisualizationDataRoute,
  WorkspaceSettingsRoute: WorkspaceSettingsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
