"""initial schema

Revision ID: 0000_initial_schema
Revises:
Create Date: 2026-05-15

"""
from collections.abc import Sequence

import sqlalchemy as sa
import sqlmodel

from alembic import op

revision: str = "0000"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspace',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('last_message_at', sa.DateTime(), nullable=True),
    sa.Column('conversation_summary', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('summary_cutoff_message_id', sa.Integer(), nullable=True),
    sa.Column('summary_updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_session_workspace_id'), 'chat_session', ['workspace_id'], unique=False)
    op.create_table('source_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('team_label', sa.Enum('MARKETING', 'PRODUCT', 'DATA_ANALYSIS', 'BUSINESS', name='teamlabel'), nullable=False),
    sa.Column('file_type', sa.Enum('CSV', 'PDF', name='sourcefiletype'), nullable=False),
    sa.Column('original_filename', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('storage_path', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_start_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_end_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('processing_status', sa.Enum('UPLOADED', 'PROCESSING', 'READY', 'FAILED', name='processingstatus'), nullable=False),
    sa.Column('processing_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('deleted_at', sa.DateTime(), nullable=True),
    sa.Column('uploaded_at', sa.DateTime(), nullable=False),
    sa.Column('processed_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_data_deleted_at'), 'source_data', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_source_data_workspace_id'), 'source_data', ['workspace_id'], unique=False)
    op.create_table('visualization_snapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('period_start_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('period_end_month', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('scope_hash', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('source_ids_json', sa.JSON(), nullable=True),
    sa.Column('artifact_ids_json', sa.JSON(), nullable=True),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('generation_error', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_visualization_snapshot_scope_hash'), 'visualization_snapshot', ['scope_hash'], unique=False)
    op.create_index(op.f('ix_visualization_snapshot_workspace_id'), 'visualization_snapshot', ['workspace_id'], unique=False)
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('USER', 'ASSISTANT', 'SYSTEM', name='chatmessagerole'), nullable=False),
    sa.Column('content', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('message_type', sa.Enum('NORMAL', 'DECISION_BRIEF', 'COMMAND_RESULT', name='chatmessagetype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'STREAMING', 'COMPLETED', 'FAILED', 'INTERRUPTED', name='messagestatus'), nullable=False),
    sa.Column('error_message', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('trace_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['session_id'], ['chat_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_chat_message_session_id'), 'chat_message', ['session_id'], unique=False)
    op.create_table('source_artifact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('artifact_type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_artifact_source_id'), 'source_artifact', ['source_id'], unique=False)
    op.create_table('source_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Enum('ANALYTICS_METRICS', 'MARKET_RESEARCH', 'PRODUCT_FEATURE', 'CUSTOMER_INSIGHT', 'BUSINESS_MODEL', 'COMPETITOR_ANALYSIS', 'REVENUE_SALES', name='categorylabel'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['source_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_source_category_source_id'), 'source_category', ['source_id'], unique=False)
    op.create_table('agent_tool_call',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('call_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('tool_name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('input_json', sa.JSON(), nullable=True),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agent_tool_call_call_id'), 'agent_tool_call', ['call_id'], unique=False)
    op.create_index(op.f('ix_agent_tool_call_message_id'), 'agent_tool_call', ['message_id'], unique=False)
    op.create_table('decision_brief',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.Integer(), nullable=False),
    sa.Column('chat_session_id', sa.Integer(), nullable=False),
    sa.Column('chat_message_id', sa.Integer(), nullable=False),
    sa.Column('sequence_number', sa.Integer(), nullable=False),
    sa.Column('context_cutoff_message_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('objective', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('recommendation_status', sa.Enum('GO', 'NO_GO', 'VALIDATE_FIRST', name='decisionrecommendationstatus'), nullable=False),
    sa.Column('approval_status', sa.Enum('DRAFT', 'REVIEWED', 'APPROVED', 'REJECTED', name='decisionapprovalstatus'), nullable=False),
    sa.Column('content_json', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.Column('status_updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['chat_message_id'], ['chat_message.id'], ),
    sa.ForeignKeyConstraint(['chat_session_id'], ['chat_session.id'], ),
    sa.ForeignKeyConstraint(['context_cutoff_message_id'], ['chat_message.id'], ),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspace.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_decision_brief_chat_message_id'), 'decision_brief', ['chat_message_id'], unique=False)
    op.create_index(op.f('ix_decision_brief_chat_session_id'), 'decision_brief', ['chat_session_id'], unique=False)
    op.create_index(op.f('ix_decision_brief_workspace_id'), 'decision_brief', ['workspace_id'], unique=False)
    op.create_table('message_source_citation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=True),
    sa.Column('artifact_id', sa.Integer(), nullable=True),
    sa.Column('chunk_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('citation_type', sa.Enum('UPLOADED_SOURCE', 'WEB', name='citationtype'), nullable=False),
    sa.Column('ordinal', sa.Integer(), nullable=True),
    sa.Column('quote', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('provider_request_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('published_date', sa.DateTime(), nullable=True),
    sa.Column('favicon_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('snippet', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('row_refs_json', sa.JSON(), nullable=True),
    sa.Column('relevance_score', sa.Float(), nullable=True),
    sa.Column('citation_status', sa.Enum('AVAILABLE', 'SOURCE_DELETED', 'SOURCE_FAILED', 'ARTIFACT_MISSING', 'WEB_UNAVAILABLE', name='citationstatus'), nullable=False),
    sa.Column('retrieved_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['artifact_id'], ['source_artifact.id'], ),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message.id'], ),
    sa.ForeignKeyConstraint(['source_id'], ['source_data.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_source_citation_message_id'), 'message_source_citation', ['message_id'], unique=False)
    op.create_index(op.f('ix_message_source_citation_source_id'), 'message_source_citation', ['source_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_source_citation_source_id'), table_name='message_source_citation')
    op.drop_index(op.f('ix_message_source_citation_message_id'), table_name='message_source_citation')
    op.drop_table('message_source_citation')
    op.drop_index(op.f('ix_decision_brief_workspace_id'), table_name='decision_brief')
    op.drop_index(op.f('ix_decision_brief_chat_session_id'), table_name='decision_brief')
    op.drop_index(op.f('ix_decision_brief_chat_message_id'), table_name='decision_brief')
    op.drop_table('decision_brief')
    op.drop_index(op.f('ix_agent_tool_call_message_id'), table_name='agent_tool_call')
    op.drop_index(op.f('ix_agent_tool_call_call_id'), table_name='agent_tool_call')
    op.drop_table('agent_tool_call')
    op.drop_index(op.f('ix_source_category_source_id'), table_name='source_category')
    op.drop_table('source_category')
    op.drop_index(op.f('ix_source_artifact_source_id'), table_name='source_artifact')
    op.drop_table('source_artifact')
    op.drop_index(op.f('ix_chat_message_session_id'), table_name='chat_message')
    op.drop_table('chat_message')
    op.drop_index(op.f('ix_visualization_snapshot_workspace_id'), table_name='visualization_snapshot')
    op.drop_index(op.f('ix_visualization_snapshot_scope_hash'), table_name='visualization_snapshot')
    op.drop_table('visualization_snapshot')
    op.drop_index(op.f('ix_source_data_workspace_id'), table_name='source_data')
    op.drop_index(op.f('ix_source_data_deleted_at'), table_name='source_data')
    op.drop_table('source_data')
    op.drop_index(op.f('ix_chat_session_workspace_id'), table_name='chat_session')
    op.drop_table('chat_session')
    op.drop_table('workspace')
    # ### end Alembic commands ###
